@env = dev

###
# OpenAPI Specification (JSON)
GET http://localhost:5134/openapi/v1.json
Accept: application/json

# OpenAPI Specification (YAML)
###
GET http://localhost:5134/openapi/v1.yaml
Accept: application/x-yaml

# Customer API Endpoint
###
GET http://localhost:5134/api/customers
Accept: application/json

# Customer API Endpoint
###
GET http://localhost:5134/api/customer
Accept: application/json

# Customer API Endpoint
###
GET http://localhost:5134/api/customer/2
Accept: application/json

# Customer API Endpoint
###
GET http://localhost:5134/api/contractors
Accept: application/json

# Customer API Endpoint
###
GET http://localhost:5134/api/contractor/1
Accept: application/json

###
